<script lang="ts" setup>
import { onMounted, ref } from 'vue'
import BookMark from './BookMark.vue'

const bookmarks = ref<chrome.bookmarks.BookmarkTreeNode[]>(import.meta.env.DEV
  ? [
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    dateAdded: 1562156820054,
                    id: '6',
                    index: 0,
                    parentId: '5',
                    title: 'エポスカード会員サイト EPOS Net',
                    url: 'https://www.eposcard.co.jp/memberservice/pc/login_for_mypage.jsp',
                  },
                  {
                    dateAdded: 1562156901989,
                    id: '7',
                    index: 1,
                    parentId: '5',
                    title: 'カード会員サービスメニュー - Yahoo!カード',
                    url: 'https://member1.card.yahoo.co.jp/',
                  },
                  {
                    dateAdded: 1562487700268,
                    id: '8',
                    index: 2,
                    parentId: '5',
                    title: 'ホーム - Dropbox',
                    url: 'https://www.dropbox.com/h',
                  },
                  {
                    dateAdded: 1565083904683,
                    id: '9',
                    index: 3,
                    parentId: '5',
                    title: 'テーブルの一覧を表示する - MySQL 逆引きリファレンス',
                    url: 'http://mysql.javarou.com/dat/000393.html',
                  },
                  {
                    dateAdded: 1566363199860,
                    id: '11',
                    index: 4,
                    parentId: '5',
                    title: 'MUFGカードWEBサービス',
                    url: 'https://www2.mufgcard.com/inet/dy/index.html',
                  },
                  {
                    dateAdded: 1569533113003,
                    id: '12',
                    index: 5,
                    parentId: '5',
                    title: 'JetBrains Account',
                    url: 'https://account.jetbrains.com/licenses',
                  },
                  {
                    dateAdded: 1683897999476,
                    id: '117',
                    index: 6,
                    parentId: '5',
                    title: 'テックビズフリーランス',
                    url: 'https://portal.techbiz.com/signin',
                  },
                  {
                    dateAdded: 1596518827940,
                    id: '14',
                    index: 7,
                    parentId: '5',
                    title: 'Pull requests · ocean-gate/leasy-front',
                    url: 'https://github.com/ocean-gate/leasy-front/pulls',
                  },
                  {
                    dateAdded: 1596756647124,
                    id: '15',
                    index: 8,
                    parentId: '5',
                    title: '【Nuxt.js】 inject is 何？ - Qiita',
                    url: 'https://qiita.com/ono-ta/items/9f2fc82882d367da220e',
                  },
                  {
                    dateAdded: 1639219476584,
                    id: '18',
                    index: 9,
                    parentId: '5',
                    title: '全国共済マイページ',
                    url: 'https://webservice.kyosai-cc.or.jp/index.html',
                  },
                  {
                    dateAdded: 1641976053560,
                    id: '19',
                    index: 10,
                    parentId: '5',
                    title: '源泉徴収票｜マネーフォワード クラウド年末調整',
                    url: 'https://tax-adjustment.moneyforward.com/my/reports/withholding_slips',
                  },
                  {
                    dateAdded: 1649066255866,
                    id: '20',
                    index: 11,
                    parentId: '5',
                    title: 'ホーム - Premier Trust',
                    url: 'https://premiertrustglobal.com/?lang=ja',
                  },
                  {
                    children: [
                      {
                        dateAdded: 1608027778465,
                        id: '17',
                        index: 0,
                        parentId: '16',
                        title: '楽天ブロードバンド メンバーズステーション',
                        url: 'https://ms.fusioncom.co.jp/rbb/members/menu/?tkn=0a4482cc77ceabae68f382e75d3d0565aef110c94a902188342f2183efc3b3d5',
                      },
                    ],
                    dateAdded: 1630077095673,
                    dateGroupModified: 1630077095673,
                    id: '16',
                    index: 12,
                    parentId: '5',
                    title: 'wifi',
                  },
                  {
                    children: [
                      {
                        dateAdded: 1654511609133,
                        id: '22',
                        index: 0,
                        parentId: '21',
                        title: '経費自動生成 - プロジェクト編集者 - Apps Script',
                        url: 'https://script.google.com/home/projects/19mtXTGa07zJUaUonW4M4471n9mNkg908KxtN0p60d4n5tMEWRpnwx9V7/edit',
                      },
                    ],
                    dateAdded: 1654511627234,
                    dateGroupModified: 1683898005245,
                    id: '21',
                    index: 13,
                    parentId: '5',
                    title: 'script',
                  },
                  {
                    dateAdded: 1673221466578,
                    id: '90',
                    index: 14,
                    parentId: '5',
                    title: 'M1 Specialty Portal',
                    url: 'https://portal.m1specialty.com/participants-portal/#/',
                  },
                  {
                    dateAdded: 1680417572244,
                    id: '105',
                    index: 15,
                    parentId: '5',
                    title: 'ホーム',
                    url: 'https://terasel.my.site.com/elsCustomer/s/',
                  },
                ],
                dateAdded: 1594005008071,
                dateGroupModified: 1683975801694,
                id: '5',
                index: 0,
                parentId: '1',
                title: '個人情報',
              },
              {
                dateAdded: 1676466934505,
                id: '98',
                index: 1,
                parentId: '1',
                title: '',
                url: 'https://www.microsoft.com/ja-jp/microsoft-365/onedrive/online-cloud-storage',
              },
              {
                dateAdded: 1606441463349,
                id: '26',
                index: 2,
                parentId: '1',
                title: '',
                url: 'https://github.com/',
              },
              {
                dateAdded: 1667520179683,
                id: '52',
                index: 3,
                parentId: '1',
                title: '',
                url: 'https://www.figma.com/files/recent?fuid=1001681988731999772',
              },
              {
                children: [
                  {
                    dateAdded: 1669478449085,
                    id: '59',
                    index: 0,
                    parentId: '60',
                    title: 'ページのインデックス登録',
                    url: 'https://search.google.com/search-console/index?resource_id=sc-domain%3Ablog.mons-plana.biz',
                  },
                  {
                    dateAdded: 1669390872792,
                    id: '58',
                    index: 1,
                    parentId: '60',
                    title: 'Web ToolBox | 開発者向けのオンラインツール',
                    url: 'https://web-toolbox.dev/',
                  },
                  {
                    children: [
                      {
                        dateAdded: 1669390486590,
                        id: '57',
                        index: 0,
                        parentId: '77',
                        title: 'mons plana (モンプラ)',
                        url: 'https://blog.mons-plana.biz/',
                      },
                      {
                        dateAdded: 1671359558160,
                        id: '78',
                        index: 1,
                        parentId: '77',
                        title: 'mons toolbox',
                        url: 'https://toolbox.mons-plana.biz/',
                      },
                      {
                        dateAdded: 1671411229423,
                        id: '79',
                        index: 2,
                        parentId: '77',
                        title: 'mons plana (モンプラ)',
                        url: 'https://mons-plana.biz/',
                      },
                    ],
                    dateAdded: 1671359525800,
                    dateGroupModified: 1671534527974,
                    id: '77',
                    index: 2,
                    parentId: '60',
                    title: 'サイト',
                  },
                  {
                    dateAdded: 1669369893223,
                    id: '54',
                    index: 3,
                    parentId: '60',
                    title: 'ファビコン作成 favicon.ico リアルタイム版 | 半透過マルチアイコンが作れます',
                    url: 'https://ao-system.net/favicon/',
                  },
                  {
                    dateAdded: 1669483540738,
                    id: '61',
                    index: 4,
                    parentId: '60',
                    title: '広告 – Google AdSense',
                    url: 'https://www.google.com/adsense/new/u/0/pub-5034622579646250/myads/units',
                  },
                  {
                    dateAdded: 1669811158192,
                    id: '63',
                    index: 5,
                    parentId: '60',
                    title: 'トップ｜A8.netメディア管理画面',
                    url: 'https://pub.a8.net/a8v2/media/memberAction.do',
                  },
                  {
                    dateAdded: 1669940844587,
                    id: '64',
                    index: 6,
                    parentId: '60',
                    title: 'Home | Mountain.09hand@gmail.com\'s Account | Cloudflare',
                    url: 'https://dash.cloudflare.com/f67b2471fb89496ac674e3ed6f2477f1',
                  },
                  {
                    dateAdded: 1669964589268,
                    id: '65',
                    index: 7,
                    parentId: '60',
                    title: 'お道具箱 for Web',
                    url: 'https://www.xn--t8ju21hu42avir.com/',
                  },
                  {
                    dateAdded: 1669979776271,
                    id: '66',
                    index: 8,
                    parentId: '60',
                    title: 'SVG Artista - SVG Drawing Animation Generator',
                    url: 'https://svgartista.net/',
                  },
                  {
                    dateAdded: 1670656874753,
                    id: '69',
                    index: 9,
                    parentId: '60',
                    title: 'アナリティクス | ホーム',
                    url: 'https://analytics.google.com/analytics/web/#/p343824601/reports/intelligenthome',
                  },
                  {
                    dateAdded: 1670660192775,
                    id: '70',
                    index: 10,
                    parentId: '60',
                    title: '検索パフォーマンス - Bing Webmaster Tools',
                    url: 'https://www.bing.com/webmasters/searchperf?siteUrl=https://blog.mons-plana.biz/',
                  },
                  {
                    dateAdded: 1670762958120,
                    id: '71',
                    index: 11,
                    parentId: '60',
                    title: '動くWebデザインアイデア帳 | 動くWebデザインアイディア帳',
                    url: 'https://coco-factory.jp/ugokuweb/',
                  },
                  {
                    dateAdded: 1670997930714,
                    id: '74',
                    index: 12,
                    parentId: '60',
                    title: 'UXライティングとは | UXライティングガイド | upwrite',
                    url: 'https://upwrite.jp/writing_uxes/',
                  },
                  {
                    dateAdded: 1671163961165,
                    id: '75',
                    index: 13,
                    parentId: '60',
                    title: 'アナリティクス | ホーム',
                    url: 'https://analytics.google.com/analytics/web/?hl=ja#/p343824601/reports/intelligenthome',
                  },
                  {
                    dateAdded: 1671359514527,
                    id: '76',
                    index: 14,
                    parentId: '60',
                    title: 'ホーム – Google AdSense',
                    url: 'https://www.google.com/adsense/new/u/0/pub-5034622579646250/home',
                  },
                  {
                    dateAdded: 1671534527974,
                    id: '80',
                    index: 15,
                    parentId: '60',
                    title: 'harlan-zw/nuxt-seo-kit: 🍱 Supercharge your Nuxt app with the all-in-one SEO layer.',
                    url: 'https://github.com/harlan-zw/nuxt-seo-kit',
                  },
                ],
                dateAdded: 1669478462838,
                dateGroupModified: 1671708232295,
                id: '60',
                index: 4,
                parentId: '1',
                title: 'ブログ関連',
              },
              {
                children: [
                  {
                    dateAdded: 1676277774704,
                    id: '92',
                    index: 0,
                    parentId: '93',
                    title: 'ARTISAN – Figma',
                    url: 'https://www.figma.com/files/team/1077404040275448496/ARTISAN?fuid=1001681988731999772',
                  },
                  {
                    dateAdded: 1676277790771,
                    id: '94',
                    index: 1,
                    parentId: '93',
                    title: '株式会社ARTISAN',
                    url: 'https://github.com/ARTISAN-inc',
                  },
                  {
                    dateAdded: 1676278603153,
                    id: '95',
                    index: 2,
                    parentId: '93',
                    title: 'Dashboards - artisan-pk - Sentry',
                    url: 'https://artisan-pk.sentry.io/dashboard/default-overview/?project=6359254',
                  },
                  {
                    dateAdded: 1676548442122,
                    id: '99',
                    index: 3,
                    parentId: '93',
                    title: 'stg 現場Hub',
                    url: 'https://stage.gembahub.jp/',
                  },
                  {
                    dateAdded: 1681208903097,
                    id: '107',
                    index: 4,
                    parentId: '93',
                    title: 'Swagger UI',
                    url: 'https://stage-api.gembahub.jp/api-docs/index.html?urls.primaryName=%E7%8F%BE%E5%A0%B4Hub%20API(Web)%20V1%20Docs',
                  },
                ],
                dateAdded: 1676277786406,
                dateGroupModified: 1681993938792,
                id: '93',
                index: 5,
                parentId: '1',
                title: '現場hub',
              },
              {
                dateAdded: 1677253027993,
                id: '101',
                index: 6,
                parentId: '1',
                title: 'Vue.jsエンジニアのためのReact入門 | Hypertext Candy',
                url: 'https://www.hypertextcandy.com/react-for-vuejs-developers',
              },
              {
                dateAdded: 1679144256059,
                id: '103',
                index: 7,
                parentId: '1',
                title: 'お世話になってるデザインの情報収集源 | Cat Knows',
                url: 'https://archived.catnose.me/example-design/',
              },
              {
                dateAdded: 1681993938792,
                id: '109',
                index: 8,
                parentId: '1',
                title: 'シュンスケ式プロンプトデザイン - シュンスケ式「プロンプトデザイン」公式Forumです。',
                url: 'https://forum.ambitiousai.co.jp/',
              },
              {
                dateAdded: 1682519864046,
                id: '111',
                index: 9,
                parentId: '1',
                title: '',
                url: 'https://322802755015.signin.aws.amazon.com/console',
              },
              {
                dateAdded: 1682815858682,
                id: '113',
                index: 10,
                parentId: '1',
                title: 'Microsoft Designer - Stunning designs in a flash',
                url: 'https://designer.microsoft.com/',
              },
              {
                dateAdded: 1683897707461,
                id: '116',
                index: 11,
                parentId: '1',
                title: 'Bard',
                url: 'https://bard.google.com/',
              },
            ],
            dateAdded: 1659412765268,
            dateGroupModified: 1683897999476,
            id: '1',
            index: 0,
            parentId: '0',
            title: 'ブックマーク バー',
          },
          {
            children: [],
            dateAdded: 1659412765268,
            id: '2',
            index: 1,
            parentId: '0',
            title: 'その他のブックマーク',
          },
          {
            children: [
              {
                dateAdded: 1453894063865,
                id: '49',
                index: 0,
                parentId: '3',
                title: 'myFIT',
                url: 'https://unipa-dai.fit.ac.jp/up/faces/up/jg/Jgc00101A.jsp',
              },
            ],
            dateAdded: 1659412765268,
            dateGroupModified: 1453894063865,
            id: '3',
            index: 2,
            parentId: '0',
            title: 'モバイルのブックマーク',
          },
        ],
        dateAdded: 1683973549112,
        id: '0',
        title: '',
      },
    ]
  : [])

onMounted(() => {
  console.log(import.meta.env.DEV)
  chrome.bookmarks.getTree((tree) => {
    bookmarks.value = tree
  },
  )
})
</script>

<template>
  <div>
    <BookMark :bookmarks="bookmarks" />
  </div>
</template>
